#!/bin/sh

TAG="$1"
OUTPUT="$2"

COMMIT=$(git rev-parse HEAD)

echo "# Version ${TAG}" > "${OUTPUT}"
echo "Possible configurations:" >> "${OUTPUT}"

for CONFIG_FILE in $(find assets/ -name '*.bso' -exec basename {} .bso \;); do
  TITLE=$(grep \#% ./assets/${CONFIG_FILE}.bso \
          | sed 's/\#%//g' \
          | sed 's/%\#//g' \
          | tr -s ' ')

  echo "###${TITLE}" >> "${OUTPUT}"
  echo "![${CONFIG_FILE}](https://github.com/m00qek/wide-snes/raw/${COMMIT}/assets/${CONFIG_FILE}.png)" >> "${OUTPUT}"
done
