name: Pull Requests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Create patch
    runs-on: ubuntu-latest
    container: "m00qek/snes-game-patcher:latest"
    steps:
    - uses: actions/checkout@v2

    - name: Download external dependencies
      run: make prepare EXECUTE=''
      env:
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}

    - name: Assemble game changes
      run: make rom EXECUTE=''

    - name: Create patch
      run: make patch EXECUTE=''

    - uses: actions/upload-artifact@v2
      with:
        name: Super Mario World Widescreen patch
        path: ./build/release/smw.bps
