name: Releases

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    container: "m00qek/snes-game-patcher:latest"
    steps:
    - uses: actions/checkout@v2

    - name: Download external dependencies
      run: make prepare EXECUTE=''
      env:
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}

    - name: Assemble game changes
      run: make rom EXECUTE=''

    - name: Create patch
      run: make patch EXECUTE=''

    - name: Create release notes
      run: make release EXECUTE='' REPO=${REPO} VERSION=${VERSION##*/}
      env:
        VERSION: ${{ github.ref }}
        REPO: ${{ github.repository }}

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "assets/*.bso,build/release/*.bps"
        bodyFile: "build/release-notes.md"
        token: ${{ secrets.GITHUB_TOKEN }}
